// <auto-generated />
using System;
using DataLabelingSupportSystem.DAL.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLabelingSupportSystem.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260114181637_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.Annotation", b =>
                {
                    b.Property<int>("AnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnotationId"));

                    b.Property<int>("DataItemSubmissionId")
                        .HasColumnType("int");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<int>("LabelId")
                        .HasColumnType("int");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("AnnotationId");

                    b.HasIndex("DataItemSubmissionId");

                    b.HasIndex("LabelId");

                    b.ToTable("annotations", (string)null);
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.DataItem", b =>
                {
                    b.Property<int>("DataItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataItemId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("DataItemId");

                    b.HasIndex("ProjectId");

                    b.ToTable("data_items", (string)null);
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.DataItemReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataItemSubmissionId")
                        .HasColumnType("int");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("DataItemSubmissionId")
                        .IsUnique();

                    b.HasIndex("ReviewerId");

                    b.ToTable("data_item_reviews", (string)null);
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.DataItemSubmission", b =>
                {
                    b.Property<int>("DataItemSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataItemSubmissionId"));

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmittedBy")
                        .HasColumnType("int");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.HasKey("DataItemSubmissionId");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("TaskItemId");

                    b.ToTable("data_item_submissions", (string)null);
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabelId"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("LabelId");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.HasIndex("ManagerId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.TaskEntity", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("AnnotatorId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("TaskId");

                    b.HasIndex("AnnotatorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskItemId"));

                    b.Property<int>("DataItemId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TaskItemId");

                    b.HasIndex("DataItemId");

                    b.HasIndex("TaskId", "DataItemId")
                        .IsUnique();

                    b.ToTable("task_items", (string)null);
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.Annotation", b =>
                {
                    b.HasOne("DataLabelingSupportSystem.DAL.Models.DataItemSubmission", "Submission")
                        .WithMany("Annotations")
                        .HasForeignKey("DataItemSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLabelingSupportSystem.DAL.Models.Label", "Label")
                        .WithMany("Annotations")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.DataItem", b =>
                {
                    b.HasOne("DataLabelingSupportSystem.DAL.Models.Project", "Project")
                        .WithMany("DataItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.DataItemReview", b =>
                {
                    b.HasOne("DataLabelingSupportSystem.DAL.Models.DataItemSubmission", "Submission")
                        .WithOne("Review")
                        .HasForeignKey("DataLabelingSupportSystem.DAL.Models.DataItemReview", "DataItemSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLabelingSupportSystem.DAL.Models.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.DataItemSubmission", b =>
                {
                    b.HasOne("DataLabelingSupportSystem.DAL.Models.User", "Submitter")
                        .WithMany("Submissions")
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLabelingSupportSystem.DAL.Models.TaskItem", "TaskItem")
                        .WithMany("Submissions")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submitter");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.Label", b =>
                {
                    b.HasOne("DataLabelingSupportSystem.DAL.Models.Project", "Project")
                        .WithMany("Labels")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.Project", b =>
                {
                    b.HasOne("DataLabelingSupportSystem.DAL.Models.User", "Manager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.TaskEntity", b =>
                {
                    b.HasOne("DataLabelingSupportSystem.DAL.Models.User", "Annotator")
                        .WithMany("Tasks")
                        .HasForeignKey("AnnotatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLabelingSupportSystem.DAL.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annotator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.TaskItem", b =>
                {
                    b.HasOne("DataLabelingSupportSystem.DAL.Models.DataItem", "DataItem")
                        .WithMany("TaskItems")
                        .HasForeignKey("DataItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLabelingSupportSystem.DAL.Models.TaskEntity", "Task")
                        .WithMany("TaskItems")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataItem");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.User", b =>
                {
                    b.HasOne("DataLabelingSupportSystem.DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.DataItem", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.DataItemSubmission", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.Label", b =>
                {
                    b.Navigation("Annotations");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.Project", b =>
                {
                    b.Navigation("DataItems");

                    b.Navigation("Labels");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.TaskEntity", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.TaskItem", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("DataLabelingSupportSystem.DAL.Models.User", b =>
                {
                    b.Navigation("ManagedProjects");

                    b.Navigation("Reviews");

                    b.Navigation("Submissions");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
